Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelwanQuestionnaires.Models;

namespace HelwanQuestionnaires.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DashboardController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Surveys = GetSurveys();
            ViewBag.Responses = GetResponses();
            return View();
        }

        private IEnumerable<Survey> GetSurveys()
        {
            return _db.Surveys
                      .Select(s => new
                          {
                              Survey = s,
                              Questions = s.Questions.Where(q => q.IsActive),
                              Responses = s.Responses
                                           .Where(r => r.CreatedBy == User.Identity.Name)
                                           .OrderByDescending(r => r.CreatedOn)
                                           .Take(1)
                          })
                      .AsEnumerable()
                      .Select(x =>
                          {
                              x.Survey.Questions = x.Questions.ToList();
                              x.Survey.Responses = x.Responses.ToList();
                              return x.Survey;
                          })
                      .OrderByDescending(s => s.IsActive)
                      .ThenBy(s => s.Name);
        }

        private IEnumerable<Response> GetResponses()
        {
            return _db.Responses
                     .Include("Survey")
                     .Include("Answers")
                     .Where(x => x.CreatedBy == User.Identity.Name)
                     .OrderByDescending(x => x.CreatedOn)
                     .ThenByDescending(x => x.Id)
                     .ToList();
        }
    }
}

Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HelwanQuestionnaires.Models;

namespace HelwanQuestionnaires.Controllers
{
    [Authorize]
    public class SurveysController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SurveysController()
        {
            _db = new ApplicationDbContext();
            
        }

        [HttpGet]
        public ActionResult Index()
        {
            var surveys = _db.Surveys.ToList();
            return View(surveys);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var survey = new Survey
                {
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now.AddYears(1)
                };

            return View(survey);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(Survey survey, string action)
        {
            if (ModelState.IsValid)
            {
                survey.Questions.ForEach(q => q.CreatedOn = q.ModifiedOn = DateTime.Now);

                _db.Surveys.Add(survey);
                _db.SaveChanges(); 

                TempData["success"] = "The survey was successfully created!";

                return RedirectToAction("Edit", new { id = survey.Id });
            }
            else
            {
                TempData["error"] = "An error occurred while attempting to create this survey.";
                return View(survey);
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var survey = _db.Surveys.Single(s => s.Id == id);

            survey.Questions = _db.Questions.Include("Choices")
                .Where(q => q.SurveyId == id)
                .OrderBy(q => q.Priority)
                .ToList();

            return View(survey);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(Survey model)
        {
            foreach (var question in model.Questions)
            {
                question.SurveyId = model.Id; 
                if (question.Id == 0)
                {
                    question.ModifiedOn = question.CreatedOn = DateTime.Now;
                    _db.Entry(question).State = EntityState.Added; 

                    foreach (var choice in question.Choices)
                    {
                        choice.QuestionId = question.Id;
                        _db.Entry(choice).State = EntityState.Added; 
                    }
                }
                else
                {
                    question.ModifiedOn = DateTime.Now;

                    var choices = _db.Choices.Where(c => c.QuestionId == question.Id).ToList(); 

                    foreach (var choice in choices)
                    {
                        _db.Entry(choice).State = EntityState.Deleted; 
                    }

                    foreach (var questionChoice in question.Choices)
                    {
                        questionChoice.Id = 0;
                        questionChoice.QuestionId = question.Id;
                        _db.Entry(questionChoice).State = EntityState.Added; 
                    }
                    
                    _db.Entry(question).State = EntityState.Modified;
                    _db.Entry(question).Property(x => x.CreatedOn).IsModified = false;
                }
            }

            
            _db.Entry(model).State = EntityState.Modified;
            
            _db.SaveChanges();
            return RedirectToAction("Edit", new { id = model.Id });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = _db.Surveys.Single(s => s.Id == id); 
            return Delete(model); 
        }

        [HttpPost]
        public ActionResult Delete(Survey survey)
        {
            _db.Entry(survey).State = EntityState.Deleted;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_FlashPartial.cshtml
@foreach (var key in TempData.Keys)
{
    <script type="text/javascript">
        $(function() {
            toastr["@(key)"]("@TempData[key]");
        });
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Academic Survey System</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/cleditor")
    @Styles.Render("~/Content/toastr")
    @Styles.Render("~/Content/site")
    <style>
        .field-validation-error {
            color: #ff0000;
        }
    </style>    

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/">Helwan Questionnaires</a>
                @Html.Partial("_MenuPartial")
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="content" class="container">
        @RenderBody()
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @Scripts.Render("~/bundles/toastr")
    @RenderSection("scripts", required: false)
    @Html.Partial("_FlashPartial")
</body>
</html>

Views/Shared/_MenuPartial.cshtml
@if (Request.IsAuthenticated)
{
    <ul class="nav">
        <li><a href="@Url.Action("Index", "Dashboard")">Home</a></li>
        <li><a href="@Url.Action("Index", "Surveys")">Admin</a></li>
    </ul>
}