Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelwanQuestionnaires.Models;

namespace HelwanQuestionnaires.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DashboardController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Surveys = GetSurveys();
            ViewBag.Responses = GetResponses();
            return View();
        }

        private IEnumerable<Survey> GetSurveys()
        {
            return _db.Surveys
                      .Select(s => new
                          {
                              Survey = s,
                              Questions = s.Questions.Where(q => q.IsActive),
                              Responses = s.Responses
                                           .Where(r => r.CreatedBy == User.Identity.Name)
                                           .OrderByDescending(r => r.CreatedOn)
                                           .Take(1)
                          })
                      .AsEnumerable()
                      .Select(x =>
                          {
                              x.Survey.Questions = x.Questions.ToList();
                              x.Survey.Responses = x.Responses.ToList();
                              return x.Survey;
                          })
                      .OrderByDescending(s => s.IsActive)
                      .ThenBy(s => s.Name);
        }

        private IEnumerable<Response> GetResponses()
        {
            return _db.Responses
                     .Include("Survey")
                     .Include("Answers")
                     .Where(x => x.CreatedBy == User.Identity.Name)
                     .OrderByDescending(x => x.CreatedOn)
                     .ThenByDescending(x => x.Id)
                     .ToList();
        }
    }
}

Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HelwanQuestionnaires.Models;
using HelwanQuestionnaires.ViewModel;

namespace HelwanQuestionnaires.Controllers
{
    [Authorize]
    public class ResponsesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ResponsesController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index(int surveyId)
        {
            var responses = _db.Responses
                               .Include("Survey")
                               .Include("Answers")
                               .Include("Answers.Question")
                               .Where(x => x.SurveyId == surveyId)
                               .OrderByDescending(x => x.CreatedOn)
                               .ThenByDescending(x => x.Id)
                               .ToList();

            return View(responses);
        }

        [HttpGet]
        public ActionResult Details(int? surveyId, int? id)
        {
            if (!(surveyId.HasValue) || !(id.HasValue))
                return new HttpStatusCodeResult(HttpStatusCode.BadGateway); 

            var response = _db.Responses
                              .Include("Survey")
                              .Include("Answers")
                              .Include("Answers.Question")
                              .Where(x => x.SurveyId == surveyId)
                              .Where(x => x.CreatedBy == User.Identity.Name)
                              .Single(x => x.Id == id);

            response.Answers = response.Answers.OrderBy(x => x.Question.Priority).ToList();
            return View(response);
        }

        [HttpGet]
        public ActionResult Create(int surveyId)
        {
            var survey = _db.Surveys
                            .Where(s => s.Id == surveyId)
                            .Select(s => new
                                {
                                    Survey = s,
                                    Questions = s.Questions
                                                 .Where(q => q.IsActive)
                                                 .OrderBy(q => q.Priority)
                                })
                             .AsEnumerable()
                             .Select(x =>
                                 {
                                     x.Survey.Questions = x.Questions.ToList();
                                     return x.Survey;
                                 })
                             .Single();

            survey.Questions = _db.Questions
                .Include("Choices")
                .Where(q => q.SurveyId == surveyId)
                .OrderBy(q => q.Priority)
                .ToList();

            var surveyModel = new SurveyViewModel
            {
                Id = surveyId,
                Name = survey.Name,
                Questions = survey.Questions
            }; 
            return View(surveyModel);
        }

        [HttpPost]
        public ActionResult Create(int surveyId, string action, Response model)
        {
            model.Answers = model.Answers.Where(a => !String.IsNullOrEmpty(a.Value)).ToList();
            model.SurveyId = surveyId;
            model.CreatedBy = User.Identity.Name;
            model.CreatedOn = DateTime.Now;
            _db.Responses.Add(model);
            _db.SaveChanges();

            TempData["success"] = "Your response was successfully saved!";

            return action == "Next"
                       ? RedirectToAction("Create", new {surveyId})
                       : RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Delete(int surveyId, int id, string returnTo)
        {
            var response = new Response() { Id = id, SurveyId = surveyId };
            _db.Entry(response).State = EntityState.Deleted;
            _db.SaveChanges();
            return Redirect(returnTo ?? Url.RouteUrl("Root"));
        }
    }
}

Views/Dashboard/Index.cshtml

@{
    ViewBag.Title = "Dashboard";
    var surveys = (IEnumerable<HelwanQuestionnaires.Models.Survey>) ViewBag.Surveys;
    var responses = (IEnumerable<HelwanQuestionnaires.Models.Response>) ViewBag.Responses;
}

@section scripts
{
    @Scripts.Render("~/bundles/models")

    <script type="text/javascript">
        $(function () {
            $('#tabs a:first').tab('show');
            ko.applyBindings(new ResponseListModel(), $('#response-list')[0]);
        })
    </script>
}

<div class="page-header">
    <h2>Surveys <small>Take surveys and view history</small></h2>
</div>

<ul id="tabs" class="nav nav-tabs">
    <li><a class="active" href="#take-survey" data-toggle="tab"><i class="icon-list-alt"></i> Surveys</a></li>
    <li><a href="#history" data-toggle="tab"><i class="icon-time"></i> History</a></li>
</ul>

<div class="tab-content">
    <div id="take-survey" class="tab-pane active">
        @foreach (var survey in surveys)
        {
            <div class="row">
                <div class="span9">
                    <h4>
                        @if (survey.IsActive)
                        {
                            <span class="label label-success">A</span>
                            <a href="@Url.Action("Create", "Responses", new { surveyId = survey.Id })">@survey.Name</a>
                        }
                        else
                        {
                            <span class="label label-important">X</span>
                            <span class="muted">@survey.Name</span>
                        }
                    </h4>
                </div>
                <div class="span3 text-right">
                    @if (survey.IsActive)
                    {
                        <a class="btn" href="@Url.Action("Create", "Responses", new { surveyId = survey.Id })">
                            Start Survey <i class="icon-arrow-right"></i>
                        </a>
                    }
                    else
                    {
                        <a class="btn disabled" href="#">Start Survey <i class="icon-arrow-right"></i></a>
                    }
                </div>
            </div>
            <div class="row">
                <div class="span4 text-left">
                    <span class="@(survey.IsActive ? "" : "muted")">
                        @survey.Questions.Count() Questions
                    </span>
                </div>
                <div class="span4 text-center">
                    <span class="@(survey.IsActive ? "" : "muted")">
                        Active: @survey.StartDate.ToString("d")
                        to @survey.EndDate.ToString("d")
                    </span>
                </div>
                <div class="span4 text-right">
                    <span class="@(survey.IsActive ? "" : "muted")">
                        Your Latest Response: 
                        @(survey.Responses.Select(x => x.CreatedOn.ToString("d")).FirstOrDefault() ?? "Never")
                    </span>
                </div>
            </div>

            <hr />
        }
    </div>
    <div id="history" class="tab-pane">
        <table id="response-list" class="table table-striped">
            <thead>
                <tr>
                    <th class="span1">Date</th>
                    <th class="span8">Survey</th>
                    <th class="span1">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var response in responses)
                {
                    <tr>
                        <td><span class="muted">@response.CreatedOn.ToString("d")</span></td>
                        <td>    
                            @Html.ActionLink(response.Survey.Name, "Details", "Responses", new {surveyId = response.SurveyId, id = response.Id}, null);  
                        </td>
                        
                        <td>
                            @Html.ActionLink("Delete", "Delete",
                                             new { Controller = "Responses", surveyId = response.SurveyId, id = response.Id },
                                             new { @class = "text-error", data_bind = "click: destroy" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>